version: 2
jobs:
  build:
    docker:
      # new all-in-one docker image
      - image: fr3akyphantom/pitchblack-builder:latest
    environment:
      MANIFEST_BRANCH: 'twrp-9.0'
      PBRP_BRANCH: 'features'
      VERSION: '3.2.0'
      VENDOR: 'Amlogic'
      CODENAME: 'SDOTT0202'
      BUILD_LUNCH: 'omni_SDOTT0202-userdebug'
      TEST_BUILD: 'true'
    working_directory: /home/builder/pitchblack
    steps:
      - checkout
      - run:
          name: AIO Build
          command: |
            echo "Set GitAuth Infos too"
            git config --global user.email $bosko.brajovich@gmail.com
            git config --global user.name $Y300-0100
            git config --global color.ui true
            wget -q https://raw.githubusercontent.com/PitchBlackRecoveryProject/vendor_pb/pb/build.sh
            source build.sh ${SFUserName} ${SFPassword} ${GITHUB_TOKEN}
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: org-global