version: 2.1

executors:
  alpine:
    docker:
      - image: fr3akyphantom/skadoosh:latest
        auth:
          username: "Y300-0100"
          password: "bosko2606"

env_legacy: &env_legacy
  RecName: "MinimalOmniRecovery"
  Link: "https://github.com/OmniROM-Legacy/minimal_manifest_twrp_omni.git"
  BRANCH: "<< parameters.platform >>"

env_minimal: &env_minimal
  RecName: "MinimalOmniRecovery"
  Link: "https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git"
  BRANCH: "<< parameters.platform >>"

default: &default
  parameters:
    platform:
      type: string
      default: ""
  steps:
    - checkout
    - run:
        name: "Compression Job for Minimal TWRP with << parameters.platform >> branch"
        command: |
          chmod a+x .circleci/keepalive.sh
          .circleci/keepalive.sh & ./script.sh ${RecName} ${Link} ${BRANCH}
          kill -s SIGTERM $(cat /tmp/keepalive.pid) || true

jobs:
  build:
    executor: alpine
    environment:
      <<: *env_minimal
    <<: *default

workflows:
  version: 2
  compress-norepo:
    jobs:
      - build:
          context: org-global
          matrix:
            parameters:
              platform: ["twrp-9.0"]